version: '3'
services:
  test:
    image: awesomeinc/puppeteer-mocha:0.13.0
    build: ./
    volumes:
      - ./test:/app/test
      - ./screenshots:/app/screenshots
    environment:
      APP_URL: http://localhost:3000
      SCREENSHOT_PATH: /app/screenshots
