version: '3'
services:
  test:
    image: awesomeinc/puppeteer-mocha:latest
    volumes:
      - ./test:/app/test
      - ./screenshots:/app/screenshots
    environment:
      APP_URL: http://localhost:3000
      SCREENSHOT_PATH: /app/screenshots
